#--------USERS---------------------

### GET All users

GET http://localhost:8080/users

### GET user by id

GET http://localhost:8080/users/167

### POST create a user

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "yulaaa",
  "email": "yulaaa@gmail.com",
  "password": "12345",
  "role": "user"
}

### DELETE all users

DELETE http://localhost:8080/users

### PUT update a user

PUT http://localhost:8080/users/177
Content-Type:application/json

{
  "username": "userNew_23",
  "role": "user",
  "password": "123",
  "email": "user@gmail.com"
}

### DELETE user by id

DELETE http://localhost:8080/users/48

### GET find by role
GET http://localhost:8080/users/searchByRole?userRole=admin


###GET user by username

GET http://localhost:8080/users/searchByUsername?username=yulia_kr

### GET user by email

GET http://localhost:8080/users/searchByEmail?email=yulia@gmail.com


#-----------PLAYLISTS-------------------------

### GET all playlists

GET http://localhost:8080/playlists

### POST playlist by userId

POST http://localhost:8080/playlists/users/229
Content-Type: application/json

{
  "name": "uhu"
}

### DELETE playlist by id

DELETE http://localhost:8080/playlists/4

### GET ALL playlists by user

GET http://localhost:8080/playlists/users/4


### POST add a song to a playlist
POST http://localhost:8080/playlists/60/songs/77

### DELETE song from a playlist

DELETE http://localhost:8080/playlists/60/songs/77

### DELETE all songs from playlist

DELETE http://localhost:8080/playlists/60/songs


### DELETE all playlists

DELETE http://localhost:8080/playlists

### GET playlist by id

GET http://localhost:8080/playlists/60

### PUT update a playlist

PUT http://localhost:8080/playlists/61
Content-Type: application/json

{
  "name": "rock mix"

}

### GET all songs from playlist

GET http://localhost:8080/playlists/60/songs






#---------SONGS------------------------

### POST add a song

POST http://localhost:8080/songs
Content-Type: application/json

{
  "artistId": "197",
  "file": null,
  "format": "MP3",
  "genre": "rap",
  "title": "Heavydirtysoul22",
  "year": "2015"
}

### GET ALL SONGS

GET http://localhost:8080/songs

### GET song by id

GET http://localhost:8080/songs/68


### DELETE song by id

DELETE http://localhost:8080/songs/69

### GET search songs by title

GET http://localhost:8080/songs/search?title=Taste


### GET search songs by genre

GET http://localhost:8080/songs/searchByGenre?genre=pop


### PUT update a song

PUT http://localhost:8080/songs/2
Content-Type: application/json

{
  "title": "My Blood",
  "year": "2018",
  "genre": "rock",
  "format": "MP3",
  "file": null,
  "artistId": "5"
}

### GET search songs by artist id

GET http://localhost:8080/songs/searchByArtistId?artistId=41

### DELETE all songs

DELETE http://localhost:8080/songs






#---------ARTISTS------------------------

### GET ARTISTS

GET http://localhost:8080/artists

### GET Artist by Id

GET http://localhost:8080/artists/188

### POST add artist

POST http://localhost:8080/artists
Content-Type: application/json

{
  "nickname": "Twenty One Pilots",
  "biography": "Best rock band"
}

### DELETE all artists

DELETE http://localhost:8080/artists


### PUT update an artist

PUT http://localhost:8080/artists/164
Content-Type: application/json

{
  "nickname": "Lana Del Ray",
  "biography": "Another pop diva"
}

### DELETE artist by id

DELETE http://localhost:8080/artists/39

### GET artist by name

GET http://localhost:8080/artists/search?name=SabrinaCarpenter



