#--------USERS---------------------

### GET All users

GET http://localhost:8080/users

### GET user by id

GET http://localhost:8080/users/1

### POST create a user

POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "yulia_kr",
  "email": "yulia@gmail.com",
  "password": "12345",
  "role": "user"
}

### DELETE all users

DELETE http://localhost:8080/users





#-----------PLAYLISTS-------------------------

### GET all playlists

GET http://localhost:8080/playlists

### POST playlist by userId

POST http://localhost:8080/playlists/users/4
Content-Type: application/json

{
  "name": "pop mix"
}

### DELETE playlist by id

DELETE http://localhost:8080/playlists/4

### GET ALL playlists by user

GET http://localhost:8080/playlists/users/4


### POST add a song to a playlist
POST http://localhost:8080/playlists/13/songs/6


### DELETE all playlists

DELETE http://localhost:8080/playlists






#---------SONGS------------------------

### POST add a song

POST http://localhost:8080/songs
Content-Type: application/json

{
  "artistId": "5",
  "file": null,
  "format": "MP3",
  "genre": "rap",
  "title": "HeavydirtySoul",
  "year": "2015"
}

### GET ALL SONGS

GET http://localhost:8080/songs

### GET search songs by title

GET http://localhost:8080/songs/search?title=Taste


### GET search songs by genre

GET http://localhost:8080/songs/searchByGenre?genre=pop


### PUT update a song

PUT http://localhost:8080/songs/2
Content-Type: application/json

{
  "title": "My Blood",
  "year": "2018",
  "genre": "rock",
  "format": "MP3",
  "file": null,
  "artistId": "5"
}

### GET search songs by artist id

GET http://localhost:8080/songs/searchByArtistId?artistId=2

### DELETE all songs

DELETE http://localhost:8080/songs






#---------ARTISTS------------------------

### GET ARTISTS

GET http://localhost:8080/artists

### GET Artist by Id

GET http://localhost:8080/artists/4

### POST add artist

POST http://localhost:8080/artists
Content-Type: application/json

{
  "nickname": "Sabrina Carpenter",
  "biography": "Pop diva of the century"
}

### DELETE all artists

DELETE http://localhost:8080/artists


### PUT update an artist

PUT http://localhost:8080/artists/6
Content-Type: application/json

{
  "nickname": "Lana Del Ray",
  "biography": "Another pop diva"
}

