version: '3.8'
name: loudly2db
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loudly2db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"

volumes:
  db_data:
